// View-only declarations from docs/pipelines/cinematic.md and the cited owner contracts.
// These descriptions do not register capabilities or compile/execute a pipeline.
export const scopes = ['pipeline', 'storytell', 'wardrobe', 'storyboard', 'filmmaker', 'montage', 'storytell:graph'] as const;
export type Scope = typeof scopes[number];
export type StageContract = {
  id: string; title: string; kind: 'input' | 'agent' | 'tool' | 'review' | 'output' | 'internal';
  summary: string; inputs: string[]; outputs: string[]; config: string; source: string;
};
const cinematic = 'docs/pipelines/cinematic.md';
export const stages: Record<string, StageContract> = {
  brief: { id: 'brief', title: 'Brief', kind: 'input', summary: 'Идея, контекст и настройки', inputs: ['Идея автора', 'Явные references и видимые production settings'], outputs: ['brief · неизменяемый submitted ввод'], config: 'Ввод фиксируется при Run. Полный cinematic Brief ещё не подключён; доступен отдельный тестовый Story input.', source: cinematic },
  storytell: { id: 'storytell', title: 'Storytell', kind: 'agent', summary: 'История и действия шотов', inputs: ['Submitted brief', 'Выбранный narrative context', 'При правке: exact previous Story и feedback'], outputs: ['story · StoryV1: hook, story, ordered shots'], config: 'Создаёт историю, не image/video prompts. Tools: обычно нет. Один bounded structured response, без придуманного model/tool-loop.', source: 'docs/agents/storytell.md' },
  'story-hitl': { id: 'story-hitl', title: 'Story review', kind: 'review', summary: 'Решение о точной Story', inputs: ['Текущая exact Story revision'], outputs: ['Та же Story с exact approval'], config: 'Approve явно утверждает exact subject; вопрос/правка адресуются Storytell. В internal Story approve ведёт в END, не Wardrobe.', source: cinematic },
  wardrobe: { id: 'wardrobe', title: 'Wardrobe', kind: 'agent', summary: 'Визуальные опоры и промпты', inputs: ['Brief', 'Approved story', 'Character/style references с явными ролями'], outputs: ['wardrobe_plan · VisualAnchorPlanV1: direction, anchor units, prompts, dependencies'], config: 'План сохраняется перед anchor-gen. Агент не ждёт рендера, не выбирает provider и не утверждает anchors. Отдельного plan gate нет.', source: 'docs/agents/wardrobe.md' },
  'anchor-gen': { id: 'anchor-gen', title: 'Anchor generation', kind: 'tool', summary: 'Варианты визуальных опор', inputs: ['Exact wardrobe_plan', 'Exact reference images и зависимости units', 'Закреплённый image profile'], outputs: ['Anchor image attempts · candidates', 'anchor_frames · выбранный полный набор после review'], config: 'Единственный writer anchor_frames. Новый face требует нового зависимого sheet; независимая location сохраняется. Provider не подключён.', source: 'docs/tools/comfyui-tool.md' },
  'anchor-hitl': { id: 'anchor-hitl', title: 'Anchor review', kind: 'review', summary: 'Выбор полного набора', inputs: ['Полный текущий anchor set', 'Exact wardrobe_plan и lineage'], outputs: ['Approved anchor_frames'], config: 'Exactly one candidate на каждый required unit. Несовместимые face/sheet отвергаются. Правка → Wardrobe; seed-only regeneration → tool. Approval открывает Storyboard только в cinematic.', source: cinematic },
  storyboard: { id: 'storyboard', title: 'Storyboard', kind: 'agent', summary: 'Начальный кадр каждого шота', inputs: ['Brief', 'Approved story', 'Exact wardrobe_plan', 'Approved anchor_frames'], outputs: ['storyboard_plan · FramePlanV1: start-frame prompts и reference bindings'], config: 'Один start frame на Story shot, в том же порядке. Показывает начало действия, не его финал. Следующий tool: frames-gen; не переписывает approved ancestors.', source: 'docs/agents/storyboard.md' },
  'frames-gen': { id: 'frames-gen', title: 'Frame generation', kind: 'tool', summary: 'Варианты начальных кадров', inputs: ['Exact storyboard_plan', 'Exact anchor_frames с обязательными ролями', 'Закреплённый image profile'], outputs: ['Frame attempts · candidates', 'story_frames · выбранные frames после review'], config: 'Все required reference roles должны дойти до workflow. Недостаточная multi-image capacity блокирует submit. Единственный writer story_frames. Provider не подключён.', source: 'docs/tools/comfyui-tool.md' },
  'frames-hitl': { id: 'frames-hitl', title: 'Frame review', kind: 'review', summary: 'Проверка всех start frames', inputs: ['Полный текущий frame set', 'Exact storyboard_plan'], outputs: ['Approved story_frames'], config: 'Один frame на каждый Story shot. Правка адресуется Storyboard и возвращается через frames-gen. Approved Story/anchors не меняются.', source: cinematic },
  filmmaker: { id: 'filmmaker', title: 'Filmmaker', kind: 'agent', summary: 'Движение внутри шотов', inputs: ['Brief', 'Approved story в исходном порядке', 'Exact approved story_frames'], outputs: ['video_plan · MotionPlanV1: motion, start image, duration для каждого shot'], config: 'Silent i2v: каждый clip начинается с exact approved frame. Без скрытых cuts, soundtrack или замены start image. Следующий tool: video-gen.', source: 'docs/agents/filmmaker.md' },
  'video-gen': { id: 'video-gen', title: 'Video generation', kind: 'tool', summary: 'Видеодубли каждого шота', inputs: ['Exact video_plan', 'Exact story_frames как start images', 'Закреплённый video profile'], outputs: ['Video attempts · candidates', 'shot_videos · выбранный набор после review'], config: 'Один video на каждый Story shot, без пропусков. Reference conditioning не доказывает i2v; start-frame mapping требует проверки. Единственный writer shot_videos. Provider не подключён.', source: 'docs/tools/comfyui-tool.md' },
  'video-hitl': { id: 'video-hitl', title: 'Video review', kind: 'review', summary: 'Проверка всех видеошотов', inputs: ['Полный текущий video set', 'Exact video_plan'], outputs: ['Approved shot_videos'], config: 'Правка адресуется Filmmaker → video-gen → video-hitl. Наличие файла не означает approval. Только полный approved набор передаётся Montage.', source: cinematic },
  montage: { id: 'montage', title: 'Сборка', kind: 'tool', summary: 'Полные клипы в Story order', inputs: ['Approved shot_videos', 'Approved Story shot order', 'Brief output settings и measured metadata'], outputs: ['final_video · MontageResultV1 с provenance'], config: 'Детерминированный ffmpeg tool: все full clips, simple cuts, supported normalization, remove audio. Internal MontagePlanV1 закрепляет exact sources; не новый агент или gate.', source: 'docs/tools/montage.md' },
  'view:montage-output': { id: 'view:montage-output', title: 'Проверенный файл', kind: 'output', summary: 'Размер, длительность, silent', inputs: ['Собранный файл Montage'], outputs: ['Технически проверенный immutable final_video'], config: 'ffprobe проверяет bytes/format, dimensions, duration и отсутствие audio streams. Проверка — часть montage tool, не отдельный runtime stage или human approval.', source: 'docs/tools/montage.md' },
  final: { id: 'final', title: 'Final', kind: 'output', summary: 'Результат Montage', inputs: ['final_video · verified Montage result'], outputs: ['Просмотр / download после появления реального файла'], config: 'Поверхность выхода Montage. Не новый агент и не final HITL. Файл не создан; player/download пока недоступны.', source: cinematic },
};
export const groups = [
  { id: 'brief', title: 'Brief', stages: ['brief'] },
  { id: 'storytell', title: 'Storytell', stages: ['storytell', 'story-hitl'] },
  { id: 'wardrobe', title: 'Wardrobe', stages: ['wardrobe', 'anchor-gen', 'anchor-hitl'] },
  { id: 'storyboard', title: 'Storyboard', stages: ['storyboard', 'frames-gen', 'frames-hitl'] },
  { id: 'filmmaker', title: 'Filmmaker', stages: ['filmmaker', 'video-gen', 'video-hitl'] },
  { id: 'montage', title: 'Montage', stages: ['montage', 'view:montage-output'] },
  { id: 'final', title: 'Final', stages: ['final'] },
] as const;
// Authored source structure, not an execution/checkpoint trace. backend/story_graph.py.
export const internalStory: StageContract[] = [
  { id: '__start__', title: 'START', kind: 'internal', summary: 'Вход внутреннего графа', inputs: ['Project / execution identity, story_activation'], outputs: ['StoryState → storytell'], config: 'initial_story_state: compact refs/identities; graph state не содержит body или media.', source: 'backend/story_graph.py:initial_story_state' },
  { id: 'storytell', title: 'storytell', kind: 'internal', summary: 'Prepare → owner → commit', inputs: ['Frozen test input, shots', 'Previous Story / feedback / discussion при resume'], outputs: ['Exact story_ref / binding_revision или owner_response'], config: 'prepare_story_operation возвращает committed replay; иначе bounded produce_story и validated commit. Это функция story, не model/tool-loop.', source: 'backend/story_graph.py:story' },
  { id: 'story_prepare_review', title: 'story_prepare_review', kind: 'internal', summary: 'Подготовка exact request', inputs: ['story_ref, binding_revision'], outputs: ['review_ref: request_id, revision, digest, binding_revision'], config: 'prepare_story_review создаёт или возвращает сохранённый exact request.', source: 'backend/story_graph.py:prepare' },
  { id: 'story_wait', title: 'story_wait', kind: 'internal', summary: 'interrupt(review_ref)', inputs: ['Exact review_ref'], outputs: ['Durable decision_id после resume'], config: 'До interrupt нет side effects. Node replays при resume; decision reference валидируется.', source: 'backend/story_graph.py:wait' },
  { id: 'story_apply', title: 'story_apply', kind: 'internal', summary: 'Применение решения', inputs: ['request_id и совпадающий decision_id'], outputs: ['Approve → END', 'Clarify / revise → storytell'], config: 'apply_story_decision применяет exact решение. Command маршрутизирует: approve → __end__; clarify/revise → storytell. Никогда Wardrobe.', source: 'backend/story_graph.py:apply' },
  { id: '__end__', title: 'END', kind: 'internal', summary: 'Только Story fixture', inputs: ['approved_story · exact story_ref'], outputs: ['Завершение internal Story'], config: 'END завершает kinodel.internal-story. Не продолжает cinematic и не создаёт media.', source: 'backend/story_graph.py:build_story_graph' },
];
