const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const { resolve } = require('node:path');
const { readFileSync } = require('node:fs');
const { mkdirSync } = require('node:fs');

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
    const shots = resolve('..', 'test-results', 'screenshots', 'standalone-html', 'v05-llm-agent-sockets');
    if (process.env.CAPTURE_SCREENSHOTS) mkdirSync(shots, { recursive: true });
    const capture = async (view, name, size = 'desktop') => {
      if (process.env.CAPTURE_SCREENSHOTS) await view.screenshot({ path: resolve(shots, `screen-${name}-${size}.png`) });
    };
    const inspect = async (locator, title) => {
      await locator.click();
      await page.locator('#detail-title').getByText(title, { exact: true }).waitFor({ state: 'visible' });
    };
    const errors = [];
    const checkSockets = async () => {
      const failures = await page.evaluate(() => [...document.querySelectorAll('path[data-from]')].flatMap(path => {
        return [['from', 'output', 0], ['to', 'input', path.getTotalLength()]].flatMap(([end, side, distance]) => {
          const identity = path.dataset[end];
          const card = [...document.querySelectorAll('.node')].find(card => identity.startsWith(card.dataset.nodeId + ':'));
          const key = identity.slice(card.dataset.nodeId.length + 1);
          const row = [...card.querySelectorAll(`.port-row.${side}`)].find(row => row.dataset.port === key);
          const rect = row.querySelector('.port').getBoundingClientRect();
          const point = path.getPointAtLength(distance).matrixTransform(path.getScreenCTM());
          return Math.hypot(point.x - rect.x - rect.width / 2, point.y - rect.y - rect.height / 2) > 1 ? [identity] : [];
        });
      }));
      assert.deepEqual(failures, [], 'wire endpoints meet rendered socket centres');
    };
    page.on('pageerror', error => errors.push(error.message));
    await page.context().setOffline(true);
    await page.goto(pathToFileURL(resolve('index.html')).href);
    assert.equal(await page.locator('.node').count(), 7);
    assert.deepEqual(await page.locator('.node-title').allTextContents(),
      ['Brief', 'Storytell', 'Wardrobe', 'Storyboard', 'Filmmaker', 'Montage', 'Final']);
    assert.equal(await page.locator('.node button').count(), 0, 'nodes have no extra action buttons');
    assert.equal(await page.locator('.node-head svg').count(), 7, 'each stage has a distinct role icon');
    assert.equal(await page.locator('#connections path[data-from="brief:character"]').count(), 0, 'unselected character context has no wire');
    await capture(page, 'pipeline');
    await checkSockets();
    await page.locator('[data-node-id="brief"]').dblclick();
    assert.equal(await page.locator('.chunk-library input').count(), 2, 'Brief offers character chunks');
    await page.getByRole('checkbox', { name: 'Select Mira character chunk' }).check();
    await inspect(page.locator('[data-node-id="brief:input"]'), 'Submitted brief');
    assert.match(await page.locator('#detail-body').innerText(), /Character chunks · local draft\s+Mira/i);
    await capture(page, 'brief');
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    assert.equal(await page.locator('#connections path[data-from="brief:character"]').count(), 2, 'chosen character context reaches Storytell and Wardrobe');
    await capture(page, 'pipeline-characters');
    await checkSockets();
    await page.locator('[data-node-id="brief"]').dblclick();
    assert.ok(await page.getByRole('checkbox', { name: 'Select Mira character chunk' }).isChecked(), 'selection survives scope navigation');
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    const start = await page.locator('#world').getAttribute('style');
    await page.mouse.move(980, 750);
    await page.mouse.down();
    await page.mouse.move(935, 725, { steps: 3 });
    await page.mouse.up();
    const panned = await page.locator('#world').getAttribute('style');
    assert.notEqual(start, panned, 'background drag pans canvas');
    await page.mouse.move(980, 750);
    await page.mouse.down({ button: 'middle' });
    await page.mouse.move(950, 750, { steps: 3 });
    await page.mouse.up({ button: 'middle' });
    assert.notEqual(await page.locator('#world').getAttribute('style'), panned, 'middle drag pans canvas');
    const draggedViewport = await page.locator('#world').getAttribute('style');

    const card = page.locator('.node').filter({ hasText: 'Wardrobe' });
    const before = await card.boundingBox();
    await page.mouse.move(before.x + 45, before.y + 20);
    await page.mouse.down();
    await page.mouse.move(before.x + 105, before.y + 55, { steps: 4 });
    await page.mouse.up();
    const after = await card.boundingBox();
    assert.ok(after.x > before.x + 35 && after.y > before.y + 20, 'node can be moved');
    await inspect(card, 'Wardrobe');
    assert.match(await page.locator('.inspector').innerText(), /wardrobe → anchor-gen → anchor-hitl/);
    await card.dblclick();
    assert.equal(await page.locator('.node').count(), 6);
    assert.equal(await page.locator('.zoom-value').innerText(), '100%', 'double-click opens without zoom');
    assert.ok(await page.locator('.inspector').isHidden());
    assert.ok(await page.locator('.preview-board').count(), 'one shared anchor table');
    assert.match(await page.locator('.preview-board').innerText(), /Portrait → sheet · location independent/);
    assert.equal(await page.locator('.node.media').count(), 3);
    assert.ok(await page.locator('.connections marker').count(), 'edges have arrows');
    assert.ok(await page.locator('.node .port-row.output .port').count(), 'nodes have typed output sockets');
    const boardBefore = await page.locator('.preview-board').boundingBox();
    const portraitBefore = await page.locator('[data-node-id="hero_face"]').boundingBox();
    await page.mouse.move(boardBefore.x + 45, boardBefore.y + 19);
    await page.mouse.down();
    await page.mouse.move(boardBefore.x + 93, boardBefore.y + 50, { steps: 4 });
    await page.mouse.up();
    const boardAfter = await page.locator('.preview-board').boundingBox();
    const portraitAfter = await page.locator('[data-node-id="hero_face"]').boundingBox();
    assert.ok(boardAfter.x > boardBefore.x + 35 && portraitAfter.x > portraitBefore.x + 35, 'preview window moves with media');
    await capture(page, 'wardrobe');
    await checkSockets();
    await inspect(page.locator('.node').filter({ hasText: 'Portrait' }), 'Portrait');
    assert.match(await page.locator('.inspector').innerText(), /windswept island/);
    await inspect(page.locator('.node').filter({ hasText: 'Wardrobe sheet' }), 'Wardrobe sheet');
    assert.match(await page.locator('.inspector').innerText(), /exact selected Mira portrait/);
    assert.equal(await page.locator('.inspector img').count(), 1);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.locator('.node').filter({ hasText: 'Anchor generation' }).dblclick();
    assert.ok(await page.locator('[data-node-id="wf:864"]').count(), 'real Krea2 CLIPTextEncode');
    const assertWorkflowWires = async file => {
      const graph = JSON.parse(readFileSync(resolve('..', 'workflow', 'comfyui', file), 'utf8'));
      const wires = await page.locator('#connections path[data-from]').evaluateAll(paths => paths.map(path => ({ from: path.dataset.from, to: path.dataset.to })));
      assert.ok(wires.length > 10, 'workflow renders individual typed connections');
      for (const { from, to } of wires) {
        const [source, out] = from.slice(3).split(':');
        const destination = to.slice(3);
        const separator = destination.indexOf(':');
        const target = destination.slice(0, separator), input = destination.slice(separator + 1);
        assert.deepEqual(graph[target].inputs[input], [source, Number(out)], `${file}: ${source}:${out} → ${target}.${input}`);
        assert.equal(await page.locator(`[data-node-id="wf:${target}"] .port-row.input[data-port="${input}"]`).count(), 1);
        assert.equal(await page.locator(`[data-node-id="wf:${source}"] .port-row.output[data-port="${out}"]`).count(), 1);
      }
    };
    await assertWorkflowWires('txt2img krea2 api v1_local.json');
    await capture(page, 'comfy-krea2');
    await inspect(page.locator('[data-node-id="wf:856"]'), '8 steps · Euler a');
    assert.match(await page.locator('#detail-body').innerText(), /txt2img krea2 api v1_local\.json/);
    await page.mouse.click(1030, 850, { button: 'right' });
    assert.equal(await page.locator('#scope-title').innerText(), 'Wardrobe', 'right click returns to parent scope');
    assert.ok(await page.locator('.node img').first().evaluate(img => img.complete && img.naturalWidth > 0), 'example photos load offline');
    await page.locator('[data-node-id="hero_sheet"]').dblclick();
    assert.ok(await page.locator('[data-node-id="wf:470"]').count(), 'sheet opens real Qwen img2img input');
    await assertWorkflowWires('qwen img2img api v1.json');
    await capture(page, 'comfy-qwen');
    await page.getByRole('button', { name: 'Wardrobe', exact: true }).click();
    await inspect(page.locator('.node').filter({ hasText: 'Wardrobe sheet' }), 'Wardrobe sheet');
    assert.match(await page.locator('.inspector').innerText(), /hero_face/);
    assert.match(await page.locator('.inspector').innerText(), /PROMPT/i);
    assert.equal(await page.locator('.inspector img').count(), 1);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.locator('.node').filter({ hasText: 'Wardrobe agent' }).dblclick();
    assert.equal(await page.locator('[data-node-id="wardrobe:tool"]').count(), 1);
    assert.equal(await page.locator('#connections path[data-from]').count(), 5);
    await checkSockets();
    await capture(page, 'llm-agent');
    assert.ok(await page.locator('[data-node-id="wardrobe:plan"]').count());
    await inspect(page.locator('.node').filter({ hasText: 'Wardrobe plan' }), 'Wardrobe plan');
    assert.match(await page.locator('.inspector').innerText(), /ochre|coat/i);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    assert.equal(await page.locator('#world').getAttribute('style'), draggedViewport, 'pipeline viewport is restored');
    await page.locator('.node').filter({ hasText: 'Storytell' }).dblclick();
    await inspect(page.locator('.node').filter({ hasText: 'Storytell agent' }), 'Storytell agent');
    assert.ok(await page.locator('.inspector h3').filter({ hasText: 'Example instruction' }).count());
    assert.match(await page.locator('.inspector').innerText(), /lighthouse/i);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await page.locator('.node').filter({ hasText: 'Storyboard' }).dblclick();
    await inspect(page.locator('.node').filter({ hasText: 'Storyboard agent' }), 'Storyboard agent');
    assert.ok(await page.locator('.inspector h3').filter({ hasText: 'Example instruction' }).count());
    assert.match(await page.locator('.inspector').innerText(), /start frame/i);
    await page.getByRole('button', { name: 'Close details' }).click();
    assert.equal(await page.locator('.node.media').count(), 3, 'two previews and pending spinner under Batch generation');
    await capture(page, 'storyboard');
    assert.equal(await page.locator('[data-node-id="frames-gen"] .node-title').innerText(), 'Batch generation');
    assert.ok(await page.locator('.spinner').count());
    await page.locator('[data-node-id="frames-gen"]').dblclick();
    assert.equal(await page.locator('.node').count(), 9, '3×3 candidate canvas');
    const batchBoard = await page.locator('.preview-board').boundingBox();
    const batchFrame = await page.locator('[data-node-id="frame:1"]').boundingBox();
    await page.mouse.move(batchBoard.x + 38, batchBoard.y + 18);
    await page.mouse.down();
    await page.mouse.move(batchBoard.x + 67, batchBoard.y + 38, { steps: 3 });
    await page.mouse.up();
    assert.ok((await page.locator('[data-node-id="frame:1"]').boundingBox()).x > batchFrame.x + 20, 'batch board moves its slots');
    await capture(page, 'batch');
    await inspect(page.locator('[data-node-id="frame:1"]'), 'S01 · take 1');
    assert.match(await page.locator('.edit-field textarea').inputValue(), /Opening of the shot/);
    await page.locator('.edit-field textarea').fill('New composition at the pier');
    const seedBefore = await page.locator('.edit-field input').inputValue();
    await page.getByRole('button', { name: 'Regenerate · mock' }).click();
    assert.notEqual(await page.locator('.edit-field input').inputValue(), seedBefore, 'mock regenerate resets seed');
    assert.match(await page.locator('[data-node-id="frame:1"]').innerText(), /Queued · mock/);
    await inspect(page.locator('[data-node-id="frame:2"]'), 'S01 · take 2');
    await page.locator('.edit-field input').fill('123456');
    await page.getByRole('button', { name: 'Regenerate · mock' }).click();
    assert.equal(await page.locator('.edit-field input').inputValue(), '123456', 'explicitly edited seed is retained');
    await page.locator('[data-node-id="frame:1"]').dblclick();
    assert.ok(await page.locator('[data-node-id="wf:865"]').count(), 'frame has t2i workflow');
    await page.mouse.click(1050, 870, { button: 'right' });
    assert.equal(await page.locator('#scope-title').innerText(), 'Batch generation');
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    assert.equal(await page.locator('#scope-title').innerText(), 'Pipeline');
    await page.locator('.node').filter({ hasText: 'Storyboard' }).dblclick();
    assert.match(await page.locator('[data-node-id="frame:1"]').innerText(), /Queued · mock/, 'preview reflects local regeneration');
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await page.locator('.node').filter({ hasText: 'Filmmaker' }).dblclick();
    await inspect(page.locator('.node').filter({ hasText: 'Filmmaker agent' }), 'Filmmaker agent');
    assert.ok(await page.locator('.inspector h3').filter({ hasText: 'Example instruction' }).count());
    assert.match(await page.locator('.inspector').innerText(), /motion prompt/i);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.locator('[data-node-id="video-gen"]').dblclick();
    assert.equal(await page.locator('.node').count(), 2, 'one clip per Story shot');
    const videoBoard = await page.locator('.preview-board').boundingBox();
    const videoClip = await page.locator('[data-node-id="clip:S01"]').boundingBox();
    await page.mouse.move(videoBoard.x + 32, videoBoard.y + 18);
    await page.mouse.down();
    await page.mouse.move(videoBoard.x + 64, videoBoard.y + 42, { steps: 3 });
    await page.mouse.up();
    assert.ok((await page.locator('[data-node-id="clip:S01"]').boundingBox()).x > videoClip.x + 25, 'video board moves with clips');
    await capture(page, 'video');
    await inspect(page.locator('[data-node-id="clip:S01"]'), 'S01 clip');
    assert.match(await page.locator('#detail-body').innerText(), /Exact approved start frame/i);
    await page.getByRole('button', { name: 'Close details' }).click();
    await page.locator('[data-node-id="clip:S01"]').dblclick();
    assert.ok(await page.locator('[data-node-id="wf:157"]').count(), 'clip has real MiniMax combine node');
    await assertWorkflowWires('minimax img2vid api v1.json');
    await capture(page, 'comfy-minimax');
    await page.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await page.mouse.move(900, 720);
    await page.mouse.wheel(0, -300);
    assert.notEqual(await page.locator('.zoom-value').innerText(), '100%');
    assert.deepEqual(errors, []);

    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
    await mobile.goto(pathToFileURL(resolve('index.html')).href);
    await capture(mobile, 'pipeline', 'mobile');
    await mobile.locator('[data-node-id="brief"]').dblclick();
    await mobile.getByRole('checkbox', { name: 'Select Mira character chunk' }).check();
    await capture(mobile, 'brief', 'mobile');
    await mobile.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await mobile.getByRole('button', { name: 'Current stage' }).click();
    await mobile.locator('.node').filter({ hasText: 'Wardrobe' }).dblclick();
    assert.equal(await mobile.locator('.node').count(), 6);
    await capture(mobile, 'wardrobe', 'mobile');
    await mobile.locator('[data-node-id="wardrobe"]').dblclick();
    await capture(mobile, 'llm-agent', 'mobile');
    await mobile.getByRole('button', { name: 'Wardrobe', exact: true }).click();
    assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const agent = await mobile.locator('.node').filter({ hasText: 'Wardrobe agent' }).boundingBox();
    assert.ok(agent && agent.x >= 0 && agent.x < 390, 'stage starts at its first node');
    await mobile.getByRole('button', { name: 'Fit' }).click();
    await capture(mobile, 'wardrobe-overview', 'mobile');
    await mobile.locator('[data-node-id="hero_face"]').click();
    await mobile.locator('#detail-title').getByText('Portrait', { exact: true }).waitFor({ state: 'visible' });
    assert.equal(await mobile.locator('#detail-title').innerText(), 'Portrait');
    await mobile.getByRole('button', { name: 'Close details' }).click();
    assert.ok(await mobile.locator('.inspector').isHidden());
    await mobile.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await mobile.getByRole('button', { name: 'Fit' }).click();
    await mobile.locator('[data-node-id="storyboard"]').dblclick();
    await mobile.getByRole('button', { name: 'Fit' }).click();
    await mobile.locator('[data-node-id="frames-gen"]').dblclick();
    await capture(mobile, 'batch', 'mobile');
    await mobile.locator('[data-node-id="frame:1"]').dblclick();
    await capture(mobile, 'comfy-krea2', 'mobile');
    await mobile.getByRole('button', { name: 'Pipeline', exact: true }).click();
    await mobile.getByRole('button', { name: 'Fit' }).click();
    await mobile.locator('[data-node-id="filmmaker"]').dblclick();
    await mobile.getByRole('button', { name: 'Fit' }).click();
    await mobile.locator('[data-node-id="video-gen"]').dblclick();
    await capture(mobile, 'video', 'mobile');
    await mobile.locator('[data-node-id="clip:S01"]').dblclick();
    await capture(mobile, 'comfy-minimax', 'mobile');
    for (const view of [page, mobile]) {
      for (const scope of ['storytell', 'storyboard', 'filmmaker', 'storytell:agent', 'wardrobe:agent', 'storyboard:agent', 'filmmaker:agent']) {
        await view.evaluate(id => go(id), scope);
        await capture(view, scope.replace(':', '-'), view === page ? 'desktop' : 'mobile');
        if (view === page) await checkSockets();
      }
    }
    const touch = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
    await touch.goto(pathToFileURL(resolve('index.html')).href);
    await touch.getByRole('button', { name: 'Current stage' }).tap();
    await touch.locator('[data-node-id="wardrobe"]').tap();
    await touch.locator('[data-node-id="wardrobe"]').tap();
    assert.equal(await touch.locator('#scope-title').innerText(), 'Wardrobe', 'touch double-tap opens stage');
    console.log('Pipeline, role icons, nested ComfyUI, previews, regeneration, right-click, offline and touch: OK');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
